### ISSUE TITLE
Feature requests and query related to tiling and select tool

### ISSUE THREAD

**Issue by nnatalieyn** [Jordan-Pierce/CoralNet-Toolbox#208]
### Feature request

1. A way to tile multiple images at once with the same tile dimensions (batch tiling?). If not, it would be nice to be able to save the work area generated on a project while saving the entire project file
2. After confirming multiple annotations with the select tool, let them stay highlighted so they can be easily combined without reselecting them
3. For annotations that are underneath other annotations with 100% overlap (thus unable to be selected with the select tool), generate a way to only keep the topmost annotation and discard the bottom? Although I am aware that this problem is unique to my annotation generation method.

### Query
When combining annotations, why do some become polygons and some multi-polygons? Below I have attached a portion of my workspace, how would you differenciate between them and just generate polygons?
![Image](https://github.com/user-attachments/assets/27073ec8-1089-4f5d-9920-4414d6676005)

![Image](https://github.com/user-attachments/assets/38f0c668-1a04-4c5d-9e22-40e4360aef99)

Also, any suggestions for improving the speed of combining patches?

Thank you!

**Comment by Jordan-Pierce** [comment]
> ### Query
> When combining annotations, why do some become polygons and some multi-polygons? Below I have attached a portion of my workspace, how would you differenciate between them and just generate polygons?

Just made this update, will be apart of the next release (0.0.55).

Touching Patches combined will create a Polygon:

![Image](https://github.com/user-attachments/assets/9117b6a8-4c5b-4e33-9349-3c67608d23cb)

However Patches cannot be combined with Polygons directly (maybe I'll change this, let me know). To combine this last one, you'd need to make it into a Polygon by joining it with another

![Image](https://github.com/user-attachments/assets/17f8a1e2-4f4a-4f06-8ea4-0bf55e01fb35)

With Polygons, they (now) only need to create a graph / bridge to be combined.

![Image](https://github.com/user-attachments/assets/d38dc9ea-71c3-49dc-adcd-1c126c52a9dd)

Combined turns to:

![Image](https://github.com/user-attachments/assets/50f5cfa1-26a8-44d8-bbf9-55a4a750a35d)

However, if you have any Polygons selected that do not form a complete graph / bridge, then the operation does nothing, and None are combined:

![Image](https://github.com/user-attachments/assets/f2bcb2fb-0a61-4476-8d4e-e33a99bb3aa6)

You instead would need to combine the Poylgons that form a bridge / graph first, then combine it with a non-connected Polygon to create a MultiPolygon.

![Image](https://github.com/user-attachments/assets/d1b53b22-63d7-4f2a-9d79-370bb95bcc9d)

![Image](https://github.com/user-attachments/assets/8ceac800-17d4-4911-a9ee-a83099dcb3ca)

**Comment by Jordan-Pierce** [comment]
> 2\. After confirming multiple annotations with the select tool, let them stay highlighted so they can be easily combined without reselecting them

This has been fixed. You won't know they've been confirmed as there is no visual signal, but they are now confirmed.

**Comment by nnatalieyn** [comment]
Thank you for getting back so quickly!! These all seem like significant enhancements and I am eager to try them out. Will report back if any issues remain.


> Do those work or are you thinking something else?

This should work, but about the batch creation, how strict is the tool when it comes to input image dimensions? My images all have different dimensions (3300x3300, 3800x3800, 4500x4500, 6000x6000 etc) which all vary slightly in the exact pixel value as they were manually cropped. If I tiled my dataset at 1000x1000 size, can I still apply that same tile size across all images in batches of similar dimensions, or will the tool produce an error and not allow me to tile multiple images at once?

I think the idea to create batch inference for work areas would definitely be helpful and speed things up!
